name: duventchezmoi
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pygrib
  - numpy
  - matplotlib
  - pytest
  - black
  - flake8
  - isort
  - pre-commit
  - commitizen
  - pip
  - pip:
    - google-api-python-client
    - google-auth
    - google-auth-oauthlib
