name: Run Unit Tests with Pytest
on:
  push:
  schedule:
    - cron: "26 10 * * *"
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install external dependencies with mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
      - name: Install project's package with pip
        run: pip install .
        shell: micromamba-shell {0}
      - name: Run tests with Pytest
        run: pytest
        shell: micromamba-shell {0}
