name: Run Unit Tests with Pytest
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Mamba
          uses: actions/setup-micromamba@v1
          environment-file: environment.yml
        - name: Run tests with Pytest
          run: pytest
